/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_tedkwan_javafemjni_FemBoltzman */

#ifndef _Included_net_tedkwan_javafemjni_FemBoltzman
#define _Included_net_tedkwan_javafemjni_FemBoltzman
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_tedkwan_javafemjni_FemBoltzman
 * Method:    cFEMnLin
 * Signature: ([DLjava/lang/String;I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_net_tedkwan_javafemjni_FemBoltzman_cFEMnLin
  (JNIEnv *, jobject, jdoubleArray, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
