/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_tedkwan_javafemjni_FemPoisson */

#ifndef _Included_net_tedkwan_javafemjni_FemPoisson
#define _Included_net_tedkwan_javafemjni_FemPoisson
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_tedkwan_javafemjni_FemPoisson
 * Method:    cFEM
 * Signature: ([DLjava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_net_tedkwan_javafemjni_FemPoisson_cFEM
  (JNIEnv *, jobject, jdoubleArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
